services:
  mcp-inspector:
    build:
      context: ./docker
      dockerfile: Dockerfile.inspector
    network_mode: host
    environment:
      - CLIENT_PORT=8080
      - HOST=0.0.0.0

  file-scope:
    build:
      context: ./docker
      dockerfile: Dockerfile.file_scope
    ports:
      - "8001:8001"
    environment:
      - PORT=8001
      - HOST=0.0.0.0
    volumes:
      - ./config/filescope.json:/app/FileScopeMCP/config.json
      - ../supergateway:/code/supergateway