services:
  mcp-inspector:
    build:
      context: ./docker
      dockerfile: Dockerfile.inspector
    network_mode: host
    environment:
      - DANGEROUSLY_OMIT_AUTH=true
      - CLIENT_PORT=8080
      - HOST=127.0.0.1

  file-scope:
    build:
      context: ./docker
      dockerfile: Dockerfile.file_scope
    ports:
      - "8001:8001"
    user: "1000:1000"
    environment:
      - PORT=8001
      - HOST=127.0.0.1
    volumes:
      - ./config/filescope.json:/app/FileScopeMCP/config.json
      - ../file_scope_folder:/code/
      - ../supergateway:/code/supergateway

  github-mcp:
    build:
      context: ./docker
      dockerfile: Dockerfile.github
    ports:
      - "8002:8002"
    user: "1000:1000"
    environment:
      - GITHUB_PERSONAL_ACCESS_TOKEN=${GITHUB_PAT}
      - PORT=8002
      - HOST=127.0.0.1