FROM node:20-alpine

RUN npm install -g supergateway

RUN apk add git

WORKDIR /app

RUN git clone https://github.com/admica/FileScopeMCP

WORKDIR /app/FileScopeMCP

RUN npm install

RUN npm run build

# Environment variables will be injected from docker-compose
ENV PORT=${PORT:-8001}
ENV HOST=${HOST:-127.0.0.1}

# Using shell form to allow environment variable interpolation
CMD npx -y supergateway --stdio "npm start" --port "${PORT}" --baseUrl "http://${HOST}:${PORT}" --ssePath "/sse"

